spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oceancoding?charactorEncoding=utf-8&useSSL=false
    username: root
    password: 0352.sw131
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        #连接池中的最小空闲连接
        min-idle: 0
    timeout: 30000
  mail:
    host: smtp.163.com
    username: 13121192200@163.com
    password: ws0352
    protocol: smtp
    default-encoding: UTF-8
    port: 25
#  security:
#    user:
#      password: 123456
#      name: root
debug: true
#kafka:
#  consumer:
#    zookeeper:
#      connect:

logging:
  file:
    path: /var/log/
    name: ocean.log
#  level:
#    root: info