spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oceancoding?charactorEncoding=utf-8&useSSL=false
    username: root
    password: 0352.sw131
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
debug: true
